{
    'name': "Odoo Mates Replica",
    'company': 'Soluntec',
    'website': 'https://www.soluntec.es',
    'version': '1.0',
    'summary': 'Práctica para replicar el módulo de Odoo Mates',
    'description': 'Réplica de Odoo Mates',
    'author': 'Cain',
    'category': 'Uncategorized',
    'version': '1.0',
    'license': 'LGPL-3',
    'application': True,
    'depends': ['base', 'base_setup', 'digest'],
    'data': [
        
        'security/ir.model.access.csv',
        # 'security/security.xml',
        'views/colegio.xml',
        'views/ampa.xml',
        'views/aulas.xml',
        'views/estudiante.xml',
        'views/material.xml',
        'views/profesor.xml',
        'views/menu.xml',
        'wizard_views/wizard.xml',
        'wizard_views/wizard_ampa_create.xml',
        'wizard_views/wizard_ampa_delete.xml',
        'wizard_views/wizard_ampa_modify.xml',
        'wizard_views/wizard_colegio_create.xml',
        'wizard_views/wizard_colegio_modify.xml',
        'wizard_views/wizard_colegio_delete.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
}